export const beers = [
    {
        tap: "1",
        price: "250/300",
        name: "Бородинское Ржаное",
        brewery: "Velka Morava",
        style: "Rye Beer",
        avb: "4.7",
        ibu: "N/A",
        about: "Пиво сварено впервые в честь 200-летия Бородинского сражения. Двухсолодовое пиво, начальной плотности 14%. Обладает глубоким тёмным рубиново-коричневым цветом и характерным ароматом и вкусом бородинского хлеба.",
        link: "https://untappd.com/b/velka-morava-borodinskoe-rzhanoe-borodinskoe-rzhanoe/411126",
    },
    {
        tap: "2",
        price: "150/230",
        name: "Kolsch",
        brewery: "Siberian Urban Brewery",
        style: "Kölsch",
        avb: "5.1",
        ibu: "18",
        about: "Тут должно быть описание, но...",
        link: "https://untappd.com/b/siberian-urban-brewery-kolsch/3205470",
    },
    {
        tap: "3",
        price: "300/400",
        name: "Ingria Pale Ale",
        brewery: "AF Brew",
        style: "IPA - American",
        avb: "5.8",
        ibu: "75",
        about: "Decent replica of American-style IPA. Hopped and dry-hopped with Simcoe. The name refers to Ingria, historically disputed area located along the southern shore of the Gulf of Finland",
        link: "https://untappd.com/b/af-brew-ingria-pale-ale/222101",
    },
    {
        tap: "4",
        price: "280/350",
        name: "Ковбой Мальборо",
        brewery: "Plan B Brewery",
        style: "IPA - American",
        avb: "6.5",
        ibu: "50",
        about: "sdfgfsdfgsdfgsd sdfadsfgg asdfgsfgadss sdfgsfgh",
        link: "https://untappd.com/b/plan-b-brewery-kovboj-malboro/673144",
    },
    {
        tap: "5",
        price: "500/900",
        name: "Lobotomy PX",
        brewery: "AF Brew",
        style: "Stout - Imperial / Double",
        avb: "13.5",
        ibu: "50",
        about: "Welcome to 2021, the Year of Lobotomy PX",
        link: "https://untappd.com/b/af-brew-lobotomy-px/4380992",
    },
    {
        tap: "6",
        price: "250/300",
        name: "Бородинское Ржаное",
        brewery: "Velka Morava",
        style: "Rye Beer",
        avb: "4.7",
        ibu: "N/A",
        about: "Пиво сварено впервые в честь 200-летия Бородинского сражения. Двухсолодовое пиво, начальной плотности 14%. Обладает глубоким тёмным рубиново-коричневым цветом и характерным ароматом и вкусом бородинского хлеба.",
        link: "https://untappd.com/b/velka-morava-borodinskoe-rzhanoe-borodinskoe-rzhanoe/411126",
    },
    {
        tap: "7",
        price: "150/230",
        name: "Kolsch",
        brewery: "Siberian Urban Brewery",
        style: "Kölsch",
        avb: "5.1",
        ibu: "18",
        about: "Тут должно быть описание, но...",
        link: "https://untappd.com/b/siberian-urban-brewery-kolsch/3205470",
    },
    {
        tap: "8",
        price: "300/400",
        name: "Ingria Pale Ale",
        brewery: "AF Brew",
        style: "IPA - American",
        avb: "5.8",
        ibu: "75",
        about: "Decent replica of American-style IPA. Hopped and dry-hopped with Simcoe. The name refers to Ingria, historically disputed area located along the southern shore of the Gulf of Finland",
        link: "https://untappd.com/b/af-brew-ingria-pale-ale/222101",
    },
    {
        tap: "9",
        price: "280/350",
        name: "Ковбой Мальборо",
        brewery: "Plan B Brewery",
        style: "IPA - American",
        avb: "6.5",
        ibu: "50",
        about: "sdfgfsdfgsdfgsd sdfadsfgg asdfgsfgadss sdfgsfgh",
        link: "https://untappd.com/b/plan-b-brewery-kovboj-malboro/673144",
    },
    {
        tap: "10",
        price: "500/900",
        name: "Lobotomy PX",
        brewery: "AF Brew",
        style: "Stout - Imperial / Double",
        avb: "13.5",
        ibu: "50",
        about: "Welcome to 2021, the Year of Lobotomy PX",
        link: "https://untappd.com/b/af-brew-lobotomy-px/4380992",
    },
    {
        tap: "11",
        price: "250/300",
        name: "Бородинское Ржаное",
        brewery: "Velka Morava",
        style: "Rye Beer",
        avb: "4.7",
        ibu: "N/A",
        about: "Пиво сварено впервые в честь 200-летия Бородинского сражения. Двухсолодовое пиво, начальной плотности 14%. Обладает глубоким тёмным рубиново-коричневым цветом и характерным ароматом и вкусом бородинского хлеба.",
        link: "https://untappd.com/b/velka-morava-borodinskoe-rzhanoe-borodinskoe-rzhanoe/411126",
    },
    {
        tap: "12",
        price: "150/230",
        name: "Kolsch",
        brewery: "Siberian Urban Brewery",
        style: "Kölsch",
        avb: "5.1",
        ibu: "18",
        about: "Тут должно быть описание, но...",
        link: "https://untappd.com/b/siberian-urban-brewery-kolsch/3205470",
    },
    {
        tap: "13",
        price: "300/400",
        name: "Ingria Pale Ale",
        brewery: "AF Brew",
        style: "IPA - American",
        avb: "5.8",
        ibu: "75",
        about: "Decent replica of American-style IPA. Hopped and dry-hopped with Simcoe. The name refers to Ingria, historically disputed area located along the southern shore of the Gulf of Finland",
        link: "https://untappd.com/b/af-brew-ingria-pale-ale/222101",
    },
    {
        tap: "14",
        price: "280/350",
        name: "Ковбой Мальборо",
        brewery: "Plan B Brewery",
        style: "IPA - American",
        avb: "6.5",
        ibu: "50",
        about: "sdfgfsdfgsdfgsd sdfadsfgg asdfgsfgadss sdfgsfgh",
        link: "https://untappd.com/b/plan-b-brewery-kovboj-malboro/673144",
    },
    {
        tap: "15",
        price: "500/900",
        name: "Lobotomy PX",
        brewery: "AF Brew",
        style: "Stout - Imperial / Double",
        avb: "13.5",
        ibu: "50",
        about: "Welcome to 2021, the Year of Lobotomy PX",
        link: "https://untappd.com/b/af-brew-lobotomy-px/4380992",
    },
]

// {
//     name: "",
//         brewery: "",
//             style: "",
//                 avb: "",
//                     ibu: "",
//                         about: "",
//                             link: "",
//     },